openapi: 3.0.3
info:
  title: Trash swagger
  description: Описание сервиса создания, обновления, получение, данных о 3D моделях
  version: 0.0.1
servers:
  - url: /api/v1
paths:
  /trash/{productId}:
    post:
      parameters:
        - name: productId
          description: Id фигуры
          in: path
          schema:
            type: string
            format: uuid
          required: true
          example: 86f85e4a-0354-4121-9491-51cc1fae14e1
      operationId: createTrash
      summary: Метод добавления фигурки в корзину
      tags:
        - trashService
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      operationId: productId
      parameters:
        - name: productId
          description: Id фигуры
          in: path
          schema:
            type: string
            format: uuid
          required: true
          example: 86f85e4a-0354-4121-9491-51cc1fae14e1
      summary: Метод удаления фигурки из избранного
      tags:
        - trashService
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /trash/find:
    post:
      operationId: getTrash
      summary: Метод получение всех фигурок в корзине
      tags:
        - trashService
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindTrashRequest'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDescription'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDescription'
  schemas:
    ErrorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    FindTrashRequest:
      description: Параметры поиска
      type: object
      properties:
        pageableInfo:
          $ref: '#/components/schemas/PageableInfo'
        trashShortInfo:
          $ref: '#/components/schemas/ShortTrash'
    ShortTrash:
      description: Информация о фигурке
      type: object
      required:
        - fullName
        - email
        - permission
        - status
      properties:
        name:
          description: Название фигурки
          type: string
          example: username@mail.ru
        price:
          description: Цена фигурки
          type: integer
          example: 200
        tags:
          description: Теги
          items:
            type: string
            format: string
            example: '#Warhamer'
    PageableInfo:
      description: Параметры страницы
      type: object
      properties:
        page:
          description: >-
            Номер страницы для отображения. Поскольку все записи не
            поместятся на фронте - следует делить результат постранично
          x-title: Номер страницы для отображения
          type: integer
          example: '1'
        recordsAmount:
          description: Количество записей на одну страницу
          type: integer
          example: '20'