openapi: 3.0.3
info:
  title: Product swagger
  description: Описание сервиса создания, обновления, получение, данных о 3D моделях
  version: 0.0.1
servers:
  - url: /api/v1
paths:
  /product/{productId}:
    get:
      operationId: getProduct
      parameters:
        - name: productId
          description: Id фигуры
          in: path
          schema:
            type: string
            format: uuid
          required: true
          example: 86f85e4a-0354-4121-9491-51cc1fae14e1
      summary: Метод получения подробных данных о фигуре
      tags:
        - productService
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      operationId: updateProduct
      parameters:
        - name: productId
          description: Id фигуры
          in: path
          schema:
            type: string
            format: uuid
          required: true
          example: 86f85e4a-0354-4121-9491-51cc1fae14e1
      summary: Метод обновления данных фигуры
      tags:
        - productService
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      operationId: deleteProduct
      parameters:
        - name: productId
          description: Id фигуры
          in: path
          schema:
            type: string
            format: uuid
          required: true
          example: 86f85e4a-0354-4121-9491-51cc1fae14e1
      summary: Метод удаления фигурки
      tags:
        - productService
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /product:
    post:
      operationId: createProduct
      summary: Метод создания фигуры
      tags:
        - productService
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /products/find:
    post:
      operationId: getProducts
      summary: Метод получение всех фигурок
      tags:
        - productService
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindProductsRequest'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDescription'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDescription'
  schemas:
    ErrorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    Product:
      description: Информация о фигурке
      type: object
      required:
        - name
        - description
        - price
        - amount
        - createdDate
        - category
      properties:
        productId:
          description: Идентификатор счёта участника
          x-title: ID продукта
          type: string
          format: uuid
        name:
          description: Название фигурки
          type: string
          example: Монстрик
        description:
          description: Описание фигурки
          type: string
          example: Большой монстрик
        price:
          description: Цена фигурки
          type: number
          format: double
          example: 200.99
        amount:
          description: Колличество фигурок у продавца
          type: integer
          example: 10
        tags:
          description: Теги
          items:
            type: string
            format: string
            example: Warhamer
        #        TODO добавить подкатегории
        category:
          description: Подкатегория продукта
          type: string
          enum:
            - с1
            - с2
            - с3
          example: с1
    FindProductsRequest:
      description: Параметры поиска
      type: object
      properties:
        pageableInfo:
          $ref: '#/components/schemas/PageableInfo'
        productShortInfo:
          $ref: '#/components/schemas/ShortProduct'
    ShortProduct:
      description: Информация о фигурке
      type: object
      required:
        - fullName
        - email
        - permission
        - status
      properties:
        name:
          description: Название фигурки
          type: string
          example: Монстрик
        price:
          description: Цена фигурки
          type: integer
          example: 200
        tags:
          description: Теги
          items:
            type: string
            format: string
            example: '#Warhamer'
    PageableInfo:
      description: Параметры страницы
      type: object
      properties:
        page:
          description: >-
            Номер страницы для отображения. Поскольку все записи не
            поместятся на фронте - следует делить результат постранично
          x-title: Номер страницы для отображения
          type: integer
          example: '1'
        recordsAmount:
          description: Количество записей на одну страницу
          type: integer
          example: '20'