openapi: 3.0.3
info:
  title: Category swagger
  description: Описание сервиса создания, обновления, получение, данных о 3D моделях
  version: 0.0.1
servers:
  - url: /api/v1
paths:
  /category:
    post:
      operationId: createUser
      summary: Метод создания категории
      tags:
        - categoryService
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /categories/find:
    post:
      operationId: getCategories
      summary: Метод получение всех категорий
      tags:
        - categoryService
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                description: Список категорий
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDescription'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDescription'
  schemas:
    ErrorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    Category:
      description: Категории
      type: object
      required:
        - name
      properties:
        name:
          description: Название фигурки
          type: string
          example: Монстрик